language: node_js

node_js:
  - "7"

services:
  - mysql

env:
  APP_NAME=Travis
  APP_PORT=9910
  DB_HOST=127.0.0.1
  DB_USER=root
  DB_PASSWORD=
  DB_DATABASE=travis_db
  JWT_SECRET=a10ec58a_a0f2_4ac4_8393_c866d813b8d1
  JWT_EXPIRES_IN=1h

before_install:
  - mysql -u "root" -e 'CREATE DATABASE travis_db;'

before_script:
  - npm i -g knex
  - npm run database:latest

script:
  - npm test

after_success:
  - npm run test:coverage
