dist: trusty

language: node_js

node_js:
  - "7"

services:
  - mysql

env:
  DB_HOST=127.0.0.1
  DB_USER=root
  DB_PASSWORD=''
  DB_DATABASE=test_db
  PORT=9910
  PASSWORD_SECRET=888u88u8u
  JWT_SECRET=88u8u8u888
  JWT_EXPIRES_IN=86400

before_install:
  - mysql -u "root" -e 'CREATE DATABASE test_db;'

before_script:
  - npm run create-db

script:
  - npm test
