language: node_js

node_js:
  - "9.2.0"

services:
  - mysql

before_install:
  - mysql -u "root" -e 'CREATE DATABASE travisdb;'

before_script:
  - npm i -g knex
  - npm run db:latest

script:
  - npm test

after_success:
  - npm run test:coverage
